import type { Metadata } from 'next'
import Navbar from './navbar'

export const metadata: Metadata = {
  title: "Guidje's Portfolio",
  description: 'Generated by create next app',  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">        
      <body>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}