import type { Metadata } from "next"
import Navbar from "./navbar"
import "../styles/global.css"
import "../styles/page.css"

export const metadata: Metadata = {
  title: "Guidje's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <main>
          <Navbar />
          <section>
            <div>
              {children}
            </div>
          </section>
        </main>
      </body>
    </html>
  )
}